# Generated by Django 5.1.7 on 2025-04-03 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berry',
            name='name',
            field=models.CharField(choices=[('BLACKBERRY', 'Blackberry'), ('BLUEBERRY', 'Blueberry'), ('CURRANT', 'Currant'), ('ELDERFLOWER', 'Elderflower'), ('GOJI', 'Goji'), ('GOOSEBERRY', 'Gooseberry'), ('MULBERRY', 'Mulberry'), ('RASPBERRY', 'Raspberry'), ('STRAWBERRY', 'Strawberry')], default='Strawberry', max_length=20),
        ),
        migrations.CreateModel(
            name='Picking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date picked')),
                ('haul', models.DecimalField(decimal_places=2, max_digits=4)),
                ('berry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.berry')),
            ],
        ),
    ]
