# Generated by Django 5.2 on 2025-04-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
